version: '3'
services:
  user_auth:
    restart: always
    build: .
    ports:
      - 8081:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
