version: '3'
services:
  user_auth_api:
    restart: always
    build: ./microservices/user_auth
    ports:
      - 12001:3000
    volumes:
      - ./microservices/user_auth:/code
  user_auth_mongo:
    image: mongo
    #ports:
     # - 12002:27017
    volumes:
      - user_auth_mongodb:/data/db
volumes:
  user_auth_mongodb:
