orchestrator:
    engine: "docker"
scalers:
    whoami-compose:
        type: "docker-compose-cmd"
        project: "traefik"
        target: "whoami"
        config: "docker-compose.yaml"
        upper_count_limit: 6
        lower_count_limit: 1
    whoami2-compose:
        type: "docker-compose-cmd"
        project: "traefik"
        target: "whoami2"
        config: "docker-compose.yaml"
rules:
    whoami-cpu-scale:
        probe: "mock.sin"
        up: "> 0.5"
        down: "< 0.5"
        scaler: whoami-compose
        refresh: 3s
    whoami2-cpu-scale:
        target: "whoami2"
        probe: "swarm.cpu_average"
        up: "> 2"
        down: "< 1.5"
        scaler: whoami2-compose
        refresh: 5s
