version: '2'

services:
 traefik:
  image: traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=WARNING
  networks:
    - public
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

 whoami:
  image: emilevauge/whoami
  networks:
    - public
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:whoami.docker.localhost"

 whoami2:
  image: emilevauge/whoami
  networks:
    - public
  labels:
    - "traefik.backend=whoami2"
    - "traefik.frontend.rule=Host:whoami2.docker.localhost"

 zenscaler:
  image: zenika/zenscaler:latest
  command: -d start
  networks:
    - public
  volumes:
    - .:/app/config
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "3000:3000"

networks:
 public:
