apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: booking
  name: booking
spec:
  ports:
    - name: "12004"
      port: 12004
      targetPort: 3000
  selector:
    io.kompose.service: booking
status:
  loadBalancer: {}
