apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 5000
  selector:
    io.kompose.service: webapp
status:
  loadBalancer: {}
