#global config
global:
  scrape_interval: 5s
  evaluation_interval: 5s
  #scrape_timeout:     1m
  #query_log_file: <string>
  external_labels:
    monitor: 'codelab-monitor'
# Scrape configs only contain one scrape target
scrape_configs:
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: 
        - localhost:9090
        - docker.for.mac:9323
  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080
